#version: '3.3'

volumes:
  fpg_data_production:
  static_volume_production:
  media_volume_production:

services:
  fdb:
    image: postgres:13.10
    env_file: .env
    volumes:
      - fpg_data_production:/var/lib/postgresql/data
  backend:
    image: 66812/foodgram_backend
    env_file: .env
    depends_on:
      - fdb
    volumes:
      - media_volume_production:/app/media
      - static_volume_production:/backend_static
  frontend:
    container_name: foodgram-front
    image: 66812/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      # - ../frontend/:/app/result_build/
      - static_volume_production:/frontend_static
  nginx:
    # container_name: foodgram-proxy
    image: 66812/foodgram_nginx
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"
    volumes:
      - static_volume_production:/staticfiles/
      - media_volume_production:/media/
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
