# Generated by Django 3.2 on 2025-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_following_myuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('name', 'text'), name='unique_recipe'),
        ),
    ]
