# Generated by Django 3.2 on 2025-01-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250116_2111'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipes',
            name='unique_recipe',
        ),
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('name', 'text', 'author'), name='unique_recipe'),
        ),
    ]
