# Generated by Django 3.2 on 2025-01-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250116_2121'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('name', 'text', 'author'), name='unique_recipe'),
        ),
    ]
