# Generated by Django 3.2 on 2025-01-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipes_unique_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmation_code',
        ),
    ]
