# Generated by Django 3.2 on 2025-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
