# Generated by Django 3.2 on 2025-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_myuser_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
