# Generated by Django 3.2 on 2025-01-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20250120_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_token',
        ),
    ]
