# Generated by Django 3.2 on 2025-01-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_myuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=90, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
