# Generated by Django 3.2 on 2025-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='recipes/default.jpg', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
