# Generated by Django 3.2 on 2025-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
